version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          name: Init npm
          command: npm init -y
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install more dependencies
          command: npm install --save-dev jest jsdom
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
